#!/bin/bash
# Generate ios/corro/app/Corro.xcodeproj (project.pbxproj).
#
# Why a generator instead of a checked-in project file: a .pbxproj is a big
# opaque plist, and the parts that actually matter for this app are the four
# settings build_ios.sh injects (SDK, arch, deployment target, Rust lib path)
# plus the file list. Generating it from a short script keeps those visible and
# reviewable. `build_ios.sh` calls this only when the project is missing, so a
# hand-edited project is never overwritten.
#
# Usage: ./gen_xcodeproj.sh /path/to/Corro.xcodeproj
set -euo pipefail

PROJECT_DIR="${1:?usage: gen_xcodeproj.sh <path/to/Corro.xcodeproj>}"
APP_DIR="$(cd "$(dirname "$PROJECT_DIR")" && pwd)"
mkdir -p "$PROJECT_DIR"

# Identifiers. Xcode's format is exactly 24 uppercase hex characters, and it
# tolerates any unique value — so a fixed prefix plus a counter keeps the
# output deterministic, which makes a diff of this file meaningful (unlike the
# random ids Xcode itself generates).
hexid() { printf 'C0DE0000%016X' "$1"; }

ID_PROJECT="$(hexid 1)"
ID_TARGET="$(hexid 2)"
ID_GROUP_MAIN="$(hexid 3)"
ID_GROUP_PRODUCTS="$(hexid 4)"
ID_GROUP_APP="$(hexid 5)"
ID_PRODUCT="$(hexid 6)"
ID_SOURCES="$(hexid 7)"
ID_FRAMEWORKS="$(hexid 8)"
ID_RESOURCES="$(hexid 9)"
ID_CONFIG_LIST_PROJ="$(hexid 10)"
ID_CONFIG_LIST_TARGET="$(hexid 11)"
ID_CONFIG_PROJ_DEBUG="$(hexid 12)"
ID_CONFIG_PROJ_RELEASE="$(hexid 13)"
ID_CONFIG_TARGET_DEBUG="$(hexid 14)"
ID_CONFIG_TARGET_RELEASE="$(hexid 15)"
ID_STORYBOARD="$(hexid 16)"
ID_PLIST="$(hexid 17)"

# One identifier per source file, in a fixed order. File refs live at 0x20+,
# build files at 0x40+, so the two sets can never collide.
declare -a SRC_NAMES=("AppDelegate.m" "SceneDelegate.m" "CorroViewController.m" "CorroIosShims.m")
declare -a HDR_NAMES=("AppDelegate.h" "SceneDelegate.h" "CorroViewController.h" "CorroBridge.h")
SRC_IDS=()
HDR_IDS=()
BUILD_IDS=()
for i in "${!SRC_NAMES[@]}"; do
  SRC_IDS+=("$(hexid "$((0x21 + i))")")
  BUILD_IDS+=("$(hexid "$((0x41 + i))")")
done
for i in "${!HDR_NAMES[@]}"; do
  HDR_IDS+=("$(hexid "$((0x31 + i))")")
done
ID_BUILD_STORYBOARD="$(hexid 0x45)"

# --- source file entries ---
src_entries=""
for i in "${!SRC_NAMES[@]}"; do
  src_entries+="		${SRC_IDS[$i]} /* ${SRC_NAMES[$i]} */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.objc; path = ${SRC_NAMES[$i]}; sourceTree = \"<group>\"; };
"
done
for i in "${!HDR_NAMES[@]}"; do
  src_entries+="		${HDR_IDS[$i]} /* ${HDR_NAMES[$i]} */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = ${HDR_NAMES[$i]}; sourceTree = \"<group>\"; };
"
done
src_entries+="		${ID_STORYBOARD} /* LaunchScreen.storyboard */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; path = LaunchScreen.storyboard; sourceTree = \"<group>\"; };
"
src_entries+="		${ID_PLIST} /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = \"<group>\"; };
"

group_children=""
for i in "${!HDR_NAMES[@]}"; do
  group_children+="				${HDR_IDS[$i]} /* ${HDR_NAMES[$i]} */,
"
done
for i in "${!SRC_NAMES[@]}"; do
  group_children+="				${SRC_IDS[$i]} /* ${SRC_NAMES[$i]} */,
"
done
group_children+="				${ID_STORYBOARD} /* LaunchScreen.storyboard */,
				${ID_PLIST} /* Info.plist */,
"

build_files=""
for i in "${!SRC_NAMES[@]}"; do
  build_files+="		${BUILD_IDS[$i]} /* ${SRC_NAMES[$i]} in Sources */ = {isa = PBXBuildFile; fileRef = ${SRC_IDS[$i]} /* ${SRC_NAMES[$i]} */; };
"
done
build_files+="		${ID_BUILD_STORYBOARD} /* LaunchScreen.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = ${ID_STORYBOARD} /* LaunchScreen.storyboard */; };
"

sources_phase=""
for i in "${!SRC_NAMES[@]}"; do
  sources_phase+="				${BUILD_IDS[$i]} /* ${SRC_NAMES[$i]} in Sources */,
"
done

cat > "$PROJECT_DIR/project.pbxproj" <<PBX
// !\$*UTF8*\$!
// corro on iOS — generated by gen_xcodeproj.sh. Do not hand-edit: the parts
// that matter are the build settings build_ios.sh injects, and this script is
// the readable form of them.
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 54;
	objects = {

/* Begin PBXBuildFile section */
${build_files}/* End PBXBuildFile section */

/* Begin PBXFileReference section */
		${ID_PRODUCT} /* corro.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = corro.app; sourceTree = BUILT_PRODUCTS_DIR; };
${src_entries}/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
		${ID_FRAMEWORKS} /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		${ID_GROUP_MAIN} = {
			isa = PBXGroup;
			children = (
				${ID_GROUP_APP} /* app */,
				${ID_GROUP_PRODUCTS} /* Products */,
			);
			sourceTree = "<group>";
		};
		${ID_GROUP_PRODUCTS} /* Products */ = {
			isa = PBXGroup;
			children = (
				${ID_PRODUCT} /* corro.app */,
			);
			name = Products;
			sourceTree = "<group>";
		};
		${ID_GROUP_APP} /* app */ = {
			isa = PBXGroup;
			children = (
${group_children}			);
			name = app;
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		${ID_TARGET} /* corro */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = ${ID_CONFIG_LIST_TARGET} /* Build configuration list for PBXNativeTarget "corro" */;
			buildPhases = (
				${ID_SOURCES} /* Sources */,
				${ID_FRAMEWORKS} /* Frameworks */,
				${ID_RESOURCES} /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = corro;
			productName = corro;
			productReference = ${ID_PRODUCT} /* corro.app */;
			productType = "com.apple.product-type.application";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		${ID_PROJECT} /* Project object */ = {
			isa = PBXProject;
			attributes = {
				BuildIndependentTargetsInParallel = 1;
				LastUpgradeCheck = 1500;
				TargetAttributes = {
					${ID_TARGET} = {
						CreatedOnToolsVersion = 15.0;
					};
				};
			};
			buildConfigurationList = ${ID_CONFIG_LIST_PROJ} /* Build configuration list for PBXProject "Corro" */;
			compatibilityVersion = "Xcode 14.0";
			developmentRegion = en;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = ${ID_GROUP_MAIN};
			productRefGroup = ${ID_GROUP_PRODUCTS} /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				${ID_TARGET} /* corro */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		${ID_RESOURCES} /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				${ID_BUILD_STORYBOARD} /* LaunchScreen.storyboard in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		${ID_SOURCES} /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
${sources_phase}			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
		${ID_CONFIG_PROJ_DEBUG} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu11;
				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
			};
			name = Debug;
		};
		${ID_CONFIG_PROJ_RELEASE} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu11;
				IPHONEOS_DEPLOYMENT_TARGET = 12.0;
				SDKROOT = iphoneos;
			};
			name = Release;
		};
		${ID_CONFIG_TARGET_DEBUG} /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_STYLE = Automatic;
				INFOPLIST_FILE = Info.plist;
				// RUST_LIB_PATH must be the DIRECTORY holding
				// libcorro_ios.a (build_ios.sh passes the right one), and
				// the library itself is named via -lcorro_ios. Concatenating
				// the ".a" onto the path here produced
				// ".../libcorro_ios.a/libcorro_ios.a" - clang: no such file.
				LIBRARY_SEARCH_PATHS = (
					"\$(RUST_LIB_PATH)",
					"\$(inherited)",
				);
				OTHER_LDFLAGS = (
					"-lcorro_ios",
					"-lobjc",
					"-framework",
					"UIKit",
					"-framework",
					"CoreGraphics",
					"-framework",
					"Foundation",
				);
				PRODUCT_BUNDLE_IDENTIFIER = com.corro.corro;
				PRODUCT_NAME = corro;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Debug;
		};
		${ID_CONFIG_TARGET_RELEASE} /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				CODE_SIGN_STYLE = Automatic;
				INFOPLIST_FILE = Info.plist;
				// RUST_LIB_PATH must be the DIRECTORY holding
				// libcorro_ios.a (build_ios.sh passes the right one), and
				// the library itself is named via -lcorro_ios. Concatenating
				// the ".a" onto the path here produced
				// ".../libcorro_ios.a/libcorro_ios.a" - clang: no such file.
				LIBRARY_SEARCH_PATHS = (
					"\$(RUST_LIB_PATH)",
					"\$(inherited)",
				);
				OTHER_LDFLAGS = (
					"-lcorro_ios",
					"-lobjc",
					"-framework",
					"UIKit",
					"-framework",
					"CoreGraphics",
					"-framework",
					"Foundation",
				);
				PRODUCT_BUNDLE_IDENTIFIER = com.corro.corro;
				PRODUCT_NAME = corro;
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		${ID_CONFIG_LIST_PROJ} /* Build configuration list for PBXProject "Corro" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${ID_CONFIG_PROJ_DEBUG} /* Debug */,
				${ID_CONFIG_PROJ_RELEASE} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		${ID_CONFIG_LIST_TARGET} /* Build configuration list for PBXNativeTarget "corro" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				${ID_CONFIG_TARGET_DEBUG} /* Debug */,
				${ID_CONFIG_TARGET_RELEASE} /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
/* End XCConfigurationList section */
	};
	rootObject = ${ID_PROJECT} /* Project object */;
}
PBX

# Xcode reads the scheme from a shared location so CI can use it.
mkdir -p "$PROJECT_DIR/xcshareddata/xcschemes"
cat > "$PROJECT_DIR/xcshareddata/xcschemes/corro.xcscheme" <<SCHEME
<?xml version="1.0" encoding="UTF-8"?>
<Scheme LastUpgradeVersion="1500" version="1.7">
   <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
      <BuildActionEntries>
         <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">
            <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="${ID_TARGET}" BuildableName="corro.app" BlueprintName="corro" ReferencedContainer="container:Corro.xcodeproj"/>
         </BuildActionEntry>
      </BuildActionEntries>
   </BuildAction>
   <LaunchAction buildConfiguration="Release" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" debugServiceExtension="internal" allowLocationSimulation="YES">
      <BuildableProductRunnable runnableDebuggingMode="0">
         <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="${ID_TARGET}" BuildableName="corro.app" BlueprintName="corro" ReferencedContainer="container:Corro.xcodeproj"/>
      </BuildableProductRunnable>
   </LaunchAction>
   <ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
</Scheme>
SCHEME

echo "generated $PROJECT_DIR (app dir: $APP_DIR)"
