// GENERATED by rswidgets — do not edit.
//
// The Objective-C half of the Rust<->ObjC ABI contract for the ios backend.
// Regenerate with `RSWIDGETS_APPLE_PROJECT=<project root>` on ios; see
// rustxWidgets/src/apple_generator.rs for what is generated and, just as
// importantly, what is deliberately not (the canvas view and the text
// measurer: their bodies are behaviour, not forwarding).
//
// This header exists so the *hand-written* classes in the same target can
// adopt these declarations instead of restating them: a drift between the two
// then fails to compile in the host, rather than corrupting registers at
// runtime with a mismatched objc_msgSend.

#ifndef CORRO_IOS_GENERATED_SHIMS_H
#define CORRO_IOS_GENERATED_SHIMS_H

#import <UIKit/UIKit.h>

#pragma mark - Forwarding shims (generated)

/// Trampoline: one selector that turns a control activation into a
/// `corro_ios_callback(id)` call. The Rust side resolves this class by name.
@interface CorroIosTarget : NSObject
+ (id)targetWithCallbackId:(NSInteger)arg0;
- (void)corroFired:(id)arg0;
@end

/// Alert wrapper: `CorroIosAlert`
@interface CorroIosAlert : NSObject
+ (id)corroNewAlert;
- (void)corroSetTitle:(id)arg0;
- (void)corroAddAction:(id)arg0;
@end

#pragma mark - Layout protocol (generated category)

/// The expand/min-width protocol the shared layout code expects from any view.
@interface UIView (CorroLayout)
- (void)corroSetSpacing:(NSInteger)arg0;
- (void)corroSetFlex:(BOOL)arg0;
- (void)corroSetMinWidth:(NSInteger)arg0;
- (void)corroSetCanvasId:(NSInteger)arg0;
- (CGFloat)corroBoundsWidth;
- (CGFloat)corroBoundsHeight;
@end

#pragma mark - Hand-written, signature-checked

/// Bodies live in the host's own .m file; declared here so a signature
/// mismatch is a compile error.
@interface CorroIosText : NSObject
+ (id)measure:(id)arg0 font:(id)arg1 size:(CGFloat)arg2 slant:(NSInteger)arg3 weight:(NSInteger)arg4;
- (void)drawText:(id)arg0 ctx:(id)arg1 font:(id)arg2 x:(CGFloat)arg3 y:(CGFloat)arg4 size:(CGFloat)arg5 r:(CGFloat)arg6 g:(CGFloat)arg7 b:(CGFloat)arg8 a:(CGFloat)arg9 slant:(NSInteger)arg10 weight:(NSInteger)arg11;
@end

/// The canvas view the host must ship (see the backend's
/// `set_sheet_view_class`). Hand-written: `drawRect:` reports the laid-out
/// size before replaying Rust's draw closure, and the input methods convert
/// coordinates.
///
/// Required overrides:
///   * `drawRect:`
///   * `corroSetCanvasId:`
@interface SheetView : UIView
@end

#endif /* CORRO_IOS_GENERATED_SHIMS_H */
