// GENERATED by rswidgets — do not edit.
//
// Forwarding shims for the ios backend: see CorroGeneratedShims.h and
// rustxWidgets/src/apple_generator.rs. Every method here is pure forwarding —
// it exists so the Rust adapter's `objc_msgSend` signature has a matching
// declaration on the ObjC side.

#import "CorroGeneratedShims.h"

// The C entry points emitted by the host crate (ios/corro or macos/corro).
extern void corro_ios_callback(uint64_t callback_id);

#pragma mark - Callback trampoline

@implementation CorroIosTarget {
    NSInteger _callbackId;
}

+ (instancetype)targetWithCallbackId:(NSInteger)callbackId {
    CorroIosTarget *t = [[CorroIosTarget alloc] init];
    t->_callbackId = callbackId;
    return t;
}

- (void)corroFired:(id)sender {
    (void)sender;
    corro_ios_callback((uint64_t)_callbackId);
}

@end

#pragma mark - Alert

/// Wraps UIAlertController (iOS 8+) and UIAlertView (iOS 7) behind one
/// interface, so the Rust side calls `corroAddAction:`/`corroNewAlert` once.
@interface CorroIosAlert ()
@property (nonatomic, strong) id native;  // UIAlertController or UIAlertView
@property (nonatomic, strong) NSMutableArray<NSString *> *actions;
@end

@implementation CorroIosAlert

+ (instancetype)corroNewAlert {
    CorroIosAlert *w = [[CorroIosAlert alloc] init];
    w.actions = [NSMutableArray array];
    return w;
}

- (void)corroSetTitle:(id)title {
    if ([UIAlertController class] != nil) {
        // UIAlertController's title is only settable at construction, so the
        // title is applied when the controller is built in corroAddAction:.
        self.actions = self.actions ?: [NSMutableArray array];
        (void)title;
    } else {
        (void)title;
    }
}

- (void)corroAddAction:(id)title {
    NSString *t = (NSString *)title;
    if ([UIAlertController class] != nil) {
        UIAlertController *ac = self.native;
        if (ac == nil) {
            ac = [UIAlertController alertControllerWithTitle:nil
                                                     message:nil
                                              preferredStyle:UIAlertControllerStyleAlert];
            self.native = ac;
        }
        [ac addAction:[UIAlertAction actionWithTitle:t
                                               style:UIAlertActionStyleDefault
                                             handler:nil]];
    } else {
        UIAlertView *av = self.native;
        if (av == nil) {
            av = [[UIAlertView alloc] initWithTitle:nil
                                            message:nil
                                           delegate:nil
                                  cancelButtonTitle:nil
                                  otherButtonTitles:nil];
            self.native = av;
        }
        [av addButtonWithTitle:t];
    }
}

@end

/// Presentation lives on the view controller, matching `Dialog::present`'s
/// `corroPresentDialog:` send.
@implementation UIViewController (CorroPresent)

- (void)corroPresentDialog:(id)dialog {
    id native = [dialog valueForKey:@"native"];
    if ([native isKindOfClass:[UIAlertController class]]) {
        [self presentViewController:(UIAlertController *)native animated:YES completion:nil];
    } else if ([native isKindOfClass:[UIAlertView class]]) {
        [(UIAlertView *)native show];
    }
}

@end

#pragma mark - Layout category

@implementation UIView (CorroLayout)

- (void)corroSetSpacing:(NSInteger)arg0 {
    (void)arg0;
}

- (void)corroSetFlex:(NSInteger)arg0 {
    (void)arg0;
}

- (void)corroSetMinWidth:(NSInteger)arg0 {
    (void)arg0;
}

// the canvas id is stored on the view by the canvas class; this category provides the setter the adapter calls before the view is customised, so a plain view is also valid
- (void)corroSetCanvasId:(NSInteger)arg0 {
    (void)arg0;
}

- (CGFloat)corroBoundsWidth {
    return 0;
}

- (CGFloat)corroBoundsHeight {
    return 0;
}

@end
