//! Android resource generation helpers for rswidgets.
//!
//! A downstream Android app crate can call [`run`] from its own `build.rs`
//! (or call the individual generators) to materialise the Android resources
//! that rswidgets' Android backend expects: a Material 3 theme, the colour
//! palette it references, an adaptive launcher icon, and a manifest that
//! wires the generated view class and main activity together.
//!
//! Every generator is *additive by design*: an existing file is never
//! overwritten, so an app can start from the generated skeleton and then
//! hand-edit the result without the build fighting it. Delete a file to
//! have it regenerated.
//!
//! This module is compiled on every target (it is plain file I/O), so a
//! host-side `build.rs` can generate resources for an Android project.

use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

/// Environment variable naming the Android project root to generate into.
/// Expected layout is the conventional `<root>/app/src/main/...`.
pub const PROJECT_ENV: &str = "RSWIDGETS_ANDROID_PROJECT";

/// Default project root, relative to a crate that sits next to the Android
/// project (e.g. `corro/android/corro` from the corro workspace root).
pub const DEFAULT_PROJECT: &str = "../android/corro";

/// Package (application id) written into the generated manifest.
pub const DEFAULT_PACKAGE: &str = "com.corro";

/// Java/Kotlin namespace holding the generated activity and shims.
pub const DEFAULT_NAMESPACE: &str = "com.corro";

/// Java class rswidgets instantiates for canvases (see
/// [`crate::backends::android::set_sheet_view_class`]). Must expose a
/// `(Context, long)` constructor taking the canvas id.
pub const DEFAULT_SHEET_VIEW_CLASS: &str = "com.corro.SheetView";

/// Material Components version the generated theme parents against.
/// The AAR itself is the app's dependency to declare (rswidgets does not
/// fetch it); this constant only travels into the theme's parent style.
pub const MATERIAL3_THEME_PARENT: &str = "Theme.Material3.DayNight.NoActionBar";

/// Brand seed colour used by the generated theme and icon background.
pub const BRAND_SEED: &str = "#2E7D32";

/// Write `content` to `path` unless the file already exists.
///
/// Returns `true` when the file was created. Parent directories are created
/// as needed, so callers can describe paths without pre-creating the tree.
pub fn write_if_missing(path: &Path, content: &str) -> io::Result<bool> {
    if path.exists() {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut f = File::create(path)?;
    f.write_all(content.as_bytes())?;
    Ok(true)
}

/// `res/values/themes.xml`: Material 3 DayNight theme for the app.
pub fn generate_themes_xml(project: &Path, package: &str) -> io::Result<bool> {
    let out = project.join("app/src/main/res/values/themes.xml");
    let content = format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator). Edit freely: this file is
     only written when missing. -->
<resources>
    <style name="{package}.Theme" parent="{MATERIAL3_THEME_PARENT}">
        <item name="colorPrimary">@color/rswidgets_brand_seed</item>
        <item name="colorOnPrimary">#FFFFFF</item>
        <item name="android:windowBackground">@color/rswidgets_surface</item>
    </style>
</resources>
"#
    );
    write_if_missing(&out, &content)
}

/// `res/values/colors.xml`: the palette the generated theme references.
pub fn generate_colors_xml(project: &Path, _package: &str) -> io::Result<bool> {
    let out = project.join("app/src/main/res/values/colors.xml");
    let content = format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator); written only when missing. -->
<resources>
    <color name="rswidgets_brand_seed">{BRAND_SEED}</color>
    <color name="rswidgets_surface">#FFFBFE</color>
    <color name="rswidgets_icon_background">{BRAND_SEED}</color>
</resources>
"#
    );
    write_if_missing(&out, &content)
}

/// `res/mipmap-anydpi-v26/ic_launcher.xml`: adaptive launcher icon.
pub fn generate_adaptive_icon_xml(project: &Path, _package: &str) -> io::Result<bool> {
    let out = project.join("app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml");
    const CONTENT: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator); written only when missing. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/rswidgets_icon_background" />
    <foreground android:drawable="@drawable/rswidgets_icon_foreground" />
</adaptive-icon>
"#;
    write_if_missing(&out, CONTENT)
}

/// `res/drawable/rswidgets_icon_foreground.xml`: adaptive-icon foreground.
///
/// A neutral grid glyph — apps are expected to replace it with their own
/// artwork by writing the drawable before running the generator, or by
/// editing it afterwards (it is never overwritten).
pub fn generate_icon_foreground_xml(project: &Path, _package: &str) -> io::Result<bool> {
    let out = project.join("app/src/main/res/drawable/rswidgets_icon_foreground.xml");
    let content = r##"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator); written only when missing. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M30,30h48v48h-48z" />
    <path
        android:fillColor="#00000000"
        android:strokeColor="#1B5E20"
        android:strokeWidth="2"
        android:pathData="M30,30h48v48h-48z M46,30v48 M62,30v48 M78,30v48 M30,46h48 M30,62h48" />
</vector>
"##;
    write_if_missing(&out, content)
}

/// `AndroidManifest.xml`: package, theme, launcher activity and the
/// `minSdk`/`targetSdk` the backend is built and tested against.
pub fn generate_android_manifest(
    project: &Path,
    package: &str,
    namespace: &str,
    activity: &str,
) -> io::Result<bool> {
    let out = project.join("app/src/main/AndroidManifest.xml");
    let content = format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator); written only when missing. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{package}">
    <uses-sdk android:minSdkVersion="24" android:targetSdkVersion="36" />
    <application
        android:allowBackup="true"
        android:extractNativeLibs="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/{package}.Theme">
        <activity
            android:name="{activity}"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"#
    );
    // `namespace` is accepted for symmetry with Kotlin/Java packaging
    // conventions; the manifest itself only needs the package name and the
    // fully-qualified (or dotted, package-relative) activity class.
    let _ = namespace;
    write_if_missing(&out, &content)
}

/// `res/values/strings.xml`: the app label the manifest references.
pub fn generate_strings_xml(project: &Path, app_name: &str) -> io::Result<bool> {
    let out = project.join("app/src/main/res/values/strings.xml");
    let content = format!(
        r#"<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by rswidgets (android_generator); written only when missing. -->
<resources>
    <string name="app_name">{app_name}</string>
</resources>
"#
    );
    write_if_missing(&out, &content)
}

/// Every resource the Android backend expects, in generation order.
#[derive(Clone, Debug)]
pub struct AndroidProject {
    /// Android project root (the directory containing `app/`).
    pub root: PathBuf,
    /// Application id (`package` in the manifest).
    pub package: String,
    /// Java/Kotlin namespace for generated shims.
    pub namespace: String,
    /// Launcher activity class, package-relative (e.g. `.MainActivity`).
    pub activity: String,
    /// App label written to `strings.xml`.
    pub app_name: String,
}

impl AndroidProject {
    /// Conventional layout for an app crate sitting next to its Android
    /// project (`<root>/app/src/main/...`).
    pub fn new(root: impl Into<PathBuf>) -> Self {
        AndroidProject {
            root: root.into(),
            package: DEFAULT_PACKAGE.to_string(),
            namespace: DEFAULT_NAMESPACE.to_string(),
            activity: ".MainActivity".to_string(),
            app_name: "corro".to_string(),
        }
    }

    /// Project root from [`PROJECT_ENV`], else the workspace-relative
    /// default resolved from the crate manifest directory.
    ///
    /// Build scripts run with the *crate's* directory as cwd, so a naive
    /// `../android/corro` would resolve relative to `rustxWidgets/rswidgets`
    /// and generate into a stray tree. `CARGO_MANIFEST_DIR` plus
    /// [`DEFAULT_PROJECT`] (two levels up from that manifest) lands on the
    /// repository's Android project instead.
    pub fn from_env() -> Self {
        let root = match std::env::var(PROJECT_ENV) {
            Ok(explicit) => PathBuf::from(explicit),
            Err(_) => {
                let base = std::env::var("CARGO_MANIFEST_DIR")
                    .map(PathBuf::from)
                    .unwrap_or_else(|_| PathBuf::from("."));
                base.join("..").join("..").join(DEFAULT_PROJECT.trim_start_matches("../"))
            }
        };
        Self::new(root)
    }

    /// Write every missing resource. Returns the paths that were created.
    pub fn generate(&self) -> io::Result<Vec<PathBuf>> {
        let mut created = Vec::new();
        let paths: [PathBuf; 6] = [
            self.root.join("app/src/main/res/values/themes.xml"),
            self.root.join("app/src/main/res/values/colors.xml"),
            self.root.join("app/src/main/res/values/strings.xml"),
            self.root.join("app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"),
            self.root.join("app/src/main/res/drawable/rswidgets_icon_foreground.xml"),
            self.root.join("app/src/main/AndroidManifest.xml"),
        ];
        let wrote = [
            generate_themes_xml(&self.root, &self.package)?,
            generate_colors_xml(&self.root, &self.package)?,
            generate_strings_xml(&self.root, &self.app_name)?,
            generate_adaptive_icon_xml(&self.root, &self.package)?,
            generate_icon_foreground_xml(&self.root, &self.package)?,
            generate_android_manifest(&self.root, &self.package, &self.namespace, &self.activity)?,
        ];
        for (path, wrote) in paths.iter().zip(wrote.iter()) {
            if *wrote {
                created.push(path.clone());
            }
        }
        Ok(created)
    }
}

/// Convenience entry point for a `build.rs`: generate the conventional
/// project from [`AndroidProject::from_env`], print the created paths (so
/// `cargo build -vv` shows what appeared) and re-run only when the project
/// tree changes.
///
/// Never fails the build: a missing or read-only Android project must not
/// break a desktop build of the same crate.
pub fn run() {
    let project = AndroidProject::from_env();
    match project.generate() {
        Ok(created) => {
            for path in &created {
                println!("cargo:warning=rswidgets generated {}", path.display());
            }
        }
        Err(e) => {
            println!(
                "cargo:warning=rswidgets Android generation skipped ({e}); set {PROJECT_ENV} to an Android project root"
            );
        }
    }
    println!("cargo:rerun-if-env-changed={PROJECT_ENV}");
}
/// Generator unit tests: additive writes, manifest/theme content, path
/// resolution. Kept in-crate so `cargo test -p rswidgets` exercises them.
#[cfg(test)]
mod tests {
    use crate::android_generator::*;
    use std::fs;

    fn temp_root(tag: &str) -> std::path::PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!("rswidgets-gen-{tag}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&p);
        p
    }

    #[test]
    fn generate_creates_every_expected_file() {
        let root = temp_root("all");
        let created = AndroidProject::new(&root).generate().unwrap();
        assert_eq!(created.len(), 6, "expected six resources, got {created:?}");
        let theme = fs::read_to_string(root.join("app/src/main/res/values/themes.xml")).unwrap();
        assert!(theme.contains("com.corro.Theme"));
        assert!(theme.contains("Theme.Material3.DayNight.NoActionBar"));
        let manifest =
            fs::read_to_string(root.join("app/src/main/AndroidManifest.xml")).unwrap();
        assert!(manifest.contains("targetSdkVersion=\"36\""));
        assert!(manifest.contains("@style/com.corro.Theme"));
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn generate_never_overwrites_an_existing_file() {
        let root = temp_root("keep");
        let manifest = root.join("app/src/main/AndroidManifest.xml");
        fs::create_dir_all(manifest.parent().unwrap()).unwrap();
        fs::write(&manifest, "<!-- hand-written -->").unwrap();
        let created = AndroidProject::new(&root).generate().unwrap();
        assert!(
            !created.contains(&manifest),
            "an existing manifest must be left alone: {created:?}"
        );
        assert_eq!(fs::read_to_string(&manifest).unwrap(), "<!-- hand-written -->");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn env_var_overrides_the_default_project_root() {
        let root = temp_root("env");
        std::env::set_var(PROJECT_ENV, &root);
        let project = AndroidProject::from_env();
        std::env::remove_var(PROJECT_ENV);
        assert_eq!(project.root, root);
        let _ = fs::remove_dir_all(&root);
    }
}
