// GENERATED by rswidgets — do not edit.
//
// Forwarding shims for the macos backend: see CorroGeneratedShims.h and
// rustxWidgets/src/apple_generator.rs. Every method here is pure forwarding —
// it exists so the Rust adapter's `objc_msgSend` signature has a matching
// declaration on the ObjC side.

#import "CorroGeneratedShims.h"

// The C entry points emitted by the host crate (ios/corro or macos/corro).
extern void corro_macos_callback(uint64_t callback_id);
// Canvas callbacks, also exported by the host crate. Reached through macros so
// the generated body stays free of platform-specific strings.
extern void corro_macos_canvas_size(uint64_t canvas_id, int32_t w, int32_t h);
extern void corro_macos_canvas_draw(uint64_t canvas_id, void *ctx, int32_t w, int32_t h);
extern void corro_macos_canvas_click(uint64_t canvas_id, double x, double y);
extern int  corro_macos_canvas_key(uint64_t canvas_id, uint32_t keyval, uint32_t mods);

#define CORRO_CANVAS_SIZE(id, w, h)    corro_macos_canvas_size((id), (w), (h))
#define CORRO_CANVAS_DRAW(id, c, w, h) corro_macos_canvas_draw((id), (c), (w), (h))
#define CORRO_CANVAS_CLICK(id, x, y)   corro_macos_canvas_click((id), (x), (y))
#define CORRO_CANVAS_KEY(id, k, m)     corro_macos_canvas_key((id), (k), (m))
#define CORRO_GRAPHICS_CONTEXT()      [[NSGraphicsContext currentContext] CGContext]

#pragma mark - Callback trampoline

@implementation CorroMacTarget {
    NSInteger _callbackId;
}

+ (instancetype)targetWithCallbackId:(NSInteger)callbackId {
    CorroMacTarget *t = [[CorroMacTarget alloc] init];
    t->_callbackId = callbackId;
    return t;
}

- (void)corroFired:(id)sender {
    (void)sender;
    corro_macos_callback((uint64_t)_callbackId);
}

@end

#pragma mark - Alert

/// Wraps NSAlert. macOS has one alert class for every supported version, so
/// unlike iOS there is no version branch here — only the modal-vs-sheet choice,
/// which is the host's (a sheet when the host has a window, modal otherwise).
@interface CorroMacAlert ()
@property (nonatomic, strong) NSAlert *native;
@end

@implementation CorroMacAlert

+ (instancetype)corroNewAlert {
    CorroMacAlert *w = [[CorroMacAlert alloc] init];
    w.native = [[NSAlert alloc] init];
    [w.native addButtonWithTitle:@"OK"];
    return w;
}

- (void)corroSetTitle:(id)title {
    self.native.messageText = (NSString *)title;
}

- (void)corroAddAction:(id)title {
    [self.native addButtonWithTitle:(NSString *)title];
}

@end

/// `Dialog::present` sends `corroPresentDialog:` to the window controller.
/// A sheet needs a window; without one, run modally.
@implementation NSWindowController (CorroPresent)

- (void)corroPresentDialog:(id)dialog {
    NSAlert *alert = [dialog valueForKey:@"native"];
    if (![alert isKindOfClass:[NSAlert class]]) {
        return;
    }
    NSWindow *window = self.window;
    if (window != nil) {
        [alert beginSheetModalForWindow:window completionHandler:nil];
    } else {
        [alert runModal];
    }
}

@end

#pragma mark - Layout category

@implementation NSView (CorroLayout)

- (void)corroSetSpacing:(NSInteger)arg0 {
    (void)arg0;
}

- (void)corroSetFlex:(BOOL)arg0 {
    (void)arg0;
}

- (void)corroSetMinWidth:(NSInteger)arg0 {
    (void)arg0;
}

// the canvas id is stored on the view by the canvas class; this category provides the setter the adapter calls before the view is customised, so a plain view is also valid
- (void)corroSetCanvasId:(NSInteger)arg0 {
    (void)arg0;
}

@end

// The canvas view is hand-written by this host (ShimConfig::emit_canvas was
// false); CorroGeneratedShims.h declares its contract.

// The text measurer/drawer is hand-written by this host
// (ShimConfig::emit_text was false); the header declares its contract.
